<div style="border:2px solid #ffc107; background:#fffde7; border-radius:8px; padding:16px; margin:16px 0;">
  <p style="display:flex; align-items:center; margin-bottom:10px;">
    <span style="font-size:26px; color:#e65100; margin-right:10px;">⚠️</span>
    <span style="font-size:18px; font-weight:700; color:#b26a00;">CẢNH BÁO: Google Colab hiện đang chặn IP từ Vietcap, không sử dụng được!</span>
  </p>
  <ul style="font-size:16px; color:#333; margin-left:38px; margin-top:0;">
    <li><span style="color:#1976d2; font-weight:600;">Ưu tiên 1:</span> Hãy dùng <b>GitHub Codespaces</b> để chạy thử <code>vnstock</code> nhanh nhất. Cần có tài khoản Github</li>
    <li><span style="color:#0057c7; font-weight:600;">Ưu tiên 2:</span> Có thể thử tiếp với <b>Deepnote</b> khi cần trải nghiệm chia sẻ. Đăng nhập bằng Google để sử dụng.</li>
    <li><span style="color:#d32f2f; text-decoration:line-through;">Colab</span> <span style="color:#d32f2f;">(đang bị chặn IP, không phù hợp hiện tại)</span></li>
  </ul>
  <p style="margin-top:12px; color:#b26a00;">
    Vui lòng chọn phương án thay thế theo thứ tự trên để đảm bảo truy cập không bị gián đoạn khi thử nghiệm hoặc cài đầy đủ môi trường Python trên máy.
  </p>
</div>

<p>
  <a href="https://codespaces.new/thinh-vu/vnstock" target="_blank" style="display:inline-block; vertical-align:middle;">
    <img src="https://img.shields.io/badge/Open%20in-GitHub%20Codespaces-blue?logo=github" alt="Open in GitHub Codespaces" style="height:20px; vertical-align:middle;">
  </a>
  <a href="https://deepnote.com/workspace/Vnstockscom-3ff51cb7-3b7c-4cf5-b082-182b28b9b623/project/Vnstock-Demo-Notebooks-42230c88-0071-4aca-bfc1-70a5374f2371/notebook/2internationalmarket-4fcb5aa7832748b1a2c47eed9dda316f?utm_source=share-modal&utm_medium=product-shared-content&utm_campaign=notebook&utm_content=42230c88-0071-4aca-bfc1-70a5374f2371" target="_blank" style="display:inline-block; vertical-align:middle; margin-left:8px;">
    <img src="https://deepnote.com/favicon.ico" alt="Deepnote" style="height:22px; vertical-align:middle; border-radius:4px; margin-right:6px;">
    <span style="font-size:16px; font-weight:500; vertical-align:middle; color:#222222;">Open in Deepnote</span>
  </a>
  <a href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb" target="_blank" style="display:inline-block; vertical-align:middle; margin-left:8px;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height:20px; vertical-align:middle;">
  </a>
</p>

# Mục lục

1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

# I. Cài đặt

## Cài đặt thư viện

In [1]:
!pip install git+https://github.com/thinh-vu/vnstock

Collecting git+https://github.com/thinh-vu/vnstock
  Cloning https://github.com/thinh-vu/vnstock to /tmp/pip-req-build-77tvj3u_
  Running command git clone --filter=blob:none --quiet https://github.com/thinh-vu/vnstock /tmp/pip-req-build-77tvj3u_
  Resolved https://github.com/thinh-vu/vnstock to commit 7bc8ec5eeda5c107995975d985306405ccbc512e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (2.31.0)
Requirement already satisfied: beautifulsoup4 in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (4.14.2)
Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (2.2.1)
Requirement already satisfied: seaborn in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (0.13.2)
Requirement already satisfied: openpyxl in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (3.1.2)
Requirement already satisfied: pydantic in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (2.12.4)
Requirement already satisfied: psutil in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (6.0.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (25.0)
Requirement already satisfied: importlib-metadata>=1.0 in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (8.7.0)
Requirement already satisfied: tenacity in /home/codespace/.local/lib/python3.12/site-packages (from vnstock==3.2.7) (9.1.2)
Requirement already satisfied: vnai>=2.2.2 in /home/codespace/.python/current/lib/python3.12/site-packages (from vnstock==3.2.7) (2.2.3)
Requirement already satisfied: vnstock_ezchart>=0.0.3 in /home/codespace/.python/current/lib/python3.12/site-packages (from vnstock==3.2.7) (0.0.3)
Requirement already satisfied: zipp>=3.20 in /home/codespace/.local/lib/python3.12/site-packages (from importlib-metadata>=1.0->vnstock==3.2.7) (3.23.0)
Requirement already satisfied: cffi>=1.17.1 in /home/codespace/.local/lib/python3.12/site-packages (from vnai>=2.2.2->vnstock==3.2.7) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=1.17.1->vnai>=2.2.2->vnstock==3.2.7) (2.23)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests->vnstock==3.2.7) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests->vnstock==3.2.7) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests->vnstock==3.2.7) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests->vnstock==3.2.7) (2025.7.9)
Requirement already satisfied: squarify in /home/codespace/.local/lib/python3.12/site-packages (from vnstock_ezchart>=0.0.3->vnstock==3.2.7) (0.4.4)
Requirement already satisfied: wordcloud in /home/codespace/.local/lib/python3.12/site-packages (from vnstock_ezchart>=0.0.3->vnstock==3.2.7) (1.9.4)
Requirement already satisfied: soupsieve>1.2 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->vnstock==3.2.7) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->vnstock==3.2.7) (4.15.0)
Requirement already satisfied: et-xmlfile in /home/codespace/.local/lib/python3.12/site-packages (from openpyxl->vnstock==3.2.7) (2.0.0)
Requirement already satisfied: numpy<2,>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->vnstock==3.2.7) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->vnstock==3.2.7) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->vnstock==3.2.7) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas->vnstock==3.2.7) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->vnstock==3.2.7) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from pydantic->vnstock==3.2.7) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/codespace/.local/lib/python3.12/site-packages (from pydantic->vnstock==3.2.7) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codespace/.local/lib/python3.12/site-packages (from pydantic->vnstock==3.2.7) (0.4.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /home/codespace/.local/lib/python3.12/site-packages (from seaborn->vnstock==3.2.7) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock==3.2.7) (3.2.5)

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [1]:
## Nạp toàn bộ thư viện
from vnstock import *

#Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock import Vnstock

Non-200 response fetching content: 502

## 👋 Chào mừng bạn đến với Vnstock!
Cảm ơn bạn đã sử dụng package phân tích chứng khoán #1 tại Việt Nam
* Tài liệu: [Sổ tay hướng dẫn](https://vnstocks.com/docs)
* Cộng đồng: [Nhóm Facebook](https://facebook.com/groups/vnstock.official)
Khám phá các tính năng mới nhất và tham gia cộng đồng để nhận hỗ trợ.

# II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN

In [2]:
from vnstock.explorer.msn import Listing
Listing(api_version='20250317').search_symbol_id('USDEUR')

,symbol,symbol_id,exchange_name,exchange_code_mic,short_name,friendly_name,eng_name,description,local_name,locale
0,USDEUR,avyn9c,FOREX,FOREX,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,,US Dollar/Euro FX Cross Rate,en-us
1,,aril27,,LU,FocSIC Hi Gr LT Bd USDEURh Fa,FocSIC Hi Gr LT Bd USDEURh Fa,Focused SICAV-High Grade Long Term Bd USD (EUR...,,Focused SICAV-High Grade Long Term Bd USD (EUR...,lb-lu
2,,ar4ocw,,LU,Focused - Corp Bd USD EURh Fa,Focused - Corp Bd USD EURh Fa,Focused Fund - Corporate Bond USD (EURh) F-acc,,Focused Fund - Corporate Bond USD (EURh) F-acc,lb-lu
3,,arjffr,,LU,FS - HG Bd USD (EURh) Fa,FS - HG Bd USD (EURh) Fa,Focused SICAV - High Grade Bond USD (EURh) F-acc,,Focused SICAV - High Grade Bond USD (EURh) F-acc,lb-lu
4,,az2nc7,,LU,Foc SIC - WB LT Bd USD EURh Fa,Foc SIC - WB LT Bd USD EURh Fa,Focused SICAV-World Bank Long Term Bd USD(EURh...,,Focused SICAV-World Bank Long Term Bd USD(EURh...,lb-lu
5,,aslrm7,,LU,UBS(L)ES-LT Thms USDEURh Pa,UBS(L)ES-LT Thms USDEURh Pa,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,lb-lu
6,,arcg4c,,LU,FS - US Corp Bd USD(EURh) F-a,FS - US Corp Bd USD(EURh) F-a,Focused SICAV - US Corporate Bd USD (EURh) F-acc,,Focused SICAV - US Corporate Bd USD (EURh) F-acc,lb-lu
7,,at5dsm,,LU,UBS L BS - GC (USD)(EURh) IXa,UBS L BS - GC (USD)(EURh) IXa,UBS (Lux) Bond S - Glob Corp (USD)(EURh) I-X-a,,UBS (Lux) Bond S - Glob Corp (USD)(EURh) I-X-a,lb-lu
8,,aswj4c,,LU,UBS L BS-GD (USD)(EURh) Pa,UBS L BS-GD (USD)(EURh) Pa,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,lb-lu
9,,chn5k2,,LU,UBS L Eq S USA Gr USD EURhIA3a,UBS L Eq S USA Gr USD EURhIA3a,UBS (Lux) Eq S - USA Growth (USD) EURh I-A3-acc,,UBS (Lux) Eq S - USA Growth (USD) EURh I-A3-acc,lb-lu

# III. Truy xuất giá lịch sử: FX, Crypto, Index

## 3.1. Truy xuất theo mã symbol

### Forex

In [5]:
from vnstock import Vnstock
fx = Vnstock().fx(symbol='JPYVND', source='MSN')
df = fx.quote.history(start='2025-01-02', end='2025-03-20', interval='1D')
df.head()

2025-11-10 06:49:42 - vnstock.common.client - DEBUG - Mapped JPYVND -> ave8sm
2025-11-10 06:49:42 - vnstock.common.data - DEBUG - No mapping for AVE8SM, using as-is

RetryError: RetryError[<Future at 0x78eec444bbf0 state=finished raised ValueError>]

### Crypto

In [5]:
crypto = Vnstock().crypto(symbol='BTC', source='MSN')
df = crypto.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df.head()

2025-08-03 23:25:34 - vnstock.common.data.data_explorer - WARNING - No mapping found for C2111, using as-is

,time,open,high,low,close,volume
151,2023-01-28,6.031745e+08,6.133101e+08,5.933238e+08,6.044319e+08,664789560448527
152,2023-02-27,6.069310e+08,6.195079e+08,6.045758e+08,6.170682e+08,435920367509622
153,2023-03-29,7.106104e+08,7.191962e+08,6.986921e+08,7.141524e+08,465752494078959
154,2023-04-28,7.445415e+08,7.823358e+08,7.438716e+08,7.719185e+08,711148725265248
155,2023-05-28,6.998016e+08,7.042199e+08,6.972077e+08,7.036822e+08,206691876549075

### Index

In [4]:
index = Vnstock().world_index(symbol='DJI', source='MSN')
df = index.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df

2025-11-10 06:49:35 - vnstock.common.client - DEBUG - Mapped DJI -> a6qja2
2025-11-10 06:49:35 - vnstock.common.data - DEBUG - No mapping for A6QJA2, using as-is
2025-11-10 06:49:38 - vnstock.explorer.msn.helper - ERROR - Network error when requesting MSN API key: 504 Server Error: Gateway Time-out for url: https://assets.msn.com/resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.168&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20

ConnectionError: Failed to connect to MSN API: 504 Server Error: Gateway Time-out for url: https://assets.msn.com/resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.168&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20

## 3.2. Truy xuất theo id tương ứng symbol

Trong trường hợp mã symbol bạn cần không có sẵn trong danh sách được hỗ trợ, bạn có thể truy xuất dữ liệu theo id của mã đó được tìm kiếm ở mục `II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN`

In [7]:
# avyufr là symbol_id của USDEUR
from vnstock.explorer.msn.quote import *

fx = Quote(symbol_id='avyn9c')
fx.history(start='2020-01-01', end='2024-12-31')

           time  open  high   low  close
940  2023-08-09  0.91  0.91  0.91   0.91
941  2023-08-10  0.91  0.91   0.9   0.91
942  2023-08-11  0.91  0.91  0.91   0.91
943  2023-08-14  0.91  0.92  0.91   0.92
944  2023-08-15  0.92  0.92  0.91   0.92
...         ...   ...   ...   ...    ...
1300 2024-12-25  0.96  0.96  0.96   0.96
1301 2024-12-26  0.96  0.96  0.96   0.96
1302 2024-12-27  0.96  0.96  0.96   0.96
1303 2024-12-30  0.96  0.96  0.96   0.96
1304 2024-12-31  0.96  0.97  0.96   0.97

[365 rows x 5 columns]

In [8]:
# c2111 là symbol_id của BTC
crypto = Quote(symbol_id='c2111')
crypto.history(start='2023-01-01', end='2024-12-31', interval='1D')

,time,open,high,low,close,volume
151,2023-01-28,6.031745e+08,6.133101e+08,5.933238e+08,6.044319e+08,664789560448527
152,2023-02-27,6.069310e+08,6.195079e+08,6.045758e+08,6.170682e+08,435920367509622
153,2023-03-29,7.106104e+08,7.191962e+08,6.986921e+08,7.141524e+08,465752494078959
154,2023-04-28,7.445415e+08,7.823358e+08,7.438716e+08,7.719185e+08,711148725265248
155,2023-05-28,6.998016e+08,7.042199e+08,6.972077e+08,7.036822e+08,206691876549075
156,2023-06-27,7.982849e+08,8.023576e+08,7.845409e+08,7.928009e+08,431956567456929
157,2023-07-27,7.654227e+08,7.772027e+08,7.624933e+08,7.688067e+08,353500956423616
158,2023-08-26,6.852268e+08,6.874378e+08,6.753566e+08,6.821884e+08,324914321627586
159,2023-09-25,6.961138e+08,6.996936e+08,6.867293e+08,6.876663e+08,214571204695554
160,2023-10-25,8.662946e+08,9.205899e+08,8.611471e+08,8.878810e+08,1176847640698359
161,2023-11-24,9.800412e+08,9.858942e+08,9.670360e+08,9.766152e+08,372289493808991
162,2023-12-24,1.152679e+09,1.152771e+09,1.135372e+09,1.145539e+09,353769191859781
163,2024-01-23,1.088290e+09,1.090845e+09,1.033199e+09,1.034698e+09,820760766257051
164,2024-02-22,1.369044e+09,1.371539e+09,1.327093e+09,1.357668e+09,749686314844633
165,2024-03-23,1.715181e+09,1.744876e+09,1.633087e+09,1.670366e+09,1084295253287945
166,2024-04-22,1.702162e+09,1.721292e+09,1.683434e+09,1.700429e+09,537069028700593
167,2024-05-22,1.871094e+09,1.884278e+09,1.812116e+09,1.836876e+09,1229149236885695
168,2024-06-21,1.701310e+09,1.740036e+09,1.690508e+09,1.697862e+09,671540647958345
169,2024-07-21,1.747133e+09,1.770725e+09,1.736387e+09,1.759016e+09,498384732932785
170,2024-08-20,1.531610e+09,1.561256e+09,1.515477e+09,1.558134e+09,678614529979899
171,2024-09-19,1.579493e+09,1.614982e+09,1.550926e+09,1.614605e+09,1073546508704814
172,2024-10-19,1.765706e+09,1.806318e+09,1.759387e+09,1.791888e+09,965289151726088
173,2024-11-18,2.371726e+09,2.394631e+09,2.324144e+09,2.353063e+09,1213910672210521
174,2024-12-18,2.776944e+09,2.835551e+09,2.757591e+09,2.779822e+09,1796355465888991